# Generated by Django 3.2.7 on 2022-01-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('efirst_name', models.CharField(max_length=100)),
                ('elast_name', models.CharField(max_length=100)),
                ('esal', models.FloatField()),
                ('ebonus', models.IntegerField(default=0)),
                ('ephone', models.IntegerField(default=0)),
                ('ehire_date', models.DateField()),
                ('ename', models.CharField(max_length=100)),
                ('elocation', models.CharField(max_length=100)),
            ],
        ),
    ]
